### ISSUE TITLE
Hook request

### ISSUE THREAD

**Issue by Berthog** [AyamiKaze/Galgame_Hook_Project#1]
Hello, excuse me the question, could you add support for CMVS engine? (mainly for purplesoft stuff) I tried search for a method to repack but it's too complicated, and there's 1 or 2 hook projects/samples for this engine but only in chinese and devs aren't very active.

**Comment by AyamiKaze** [comment]
> Hello, excuse me the question, could you add support for CMVS engine? (mainly for purplesoft stuff) I tried search for a method to repack but it's too complicated, and there's 1 or 2 hook projects/samples for this engine but only in chinese and devs aren't very active.

https://github.com/AyamiKaze/GalgameNote/tree/main/cmvs_hook_tuts/code
base on amatsutsumi
